#ifndef KAMISADO_ENUM_UTILS_H
#define KAMISADO_ENUM_UTILS_H

enum GameType { SIMPLE, STANDARD, LONG, MARATHON};

enum Phase { MOVE_TOWER, FINISH};

enum Color { NONE = -1, BLACK, WHITE};

enum TowerColor {ORANGE, BLUE, PURPLE, PINK, YELLOW, RED, GREEN, BROWN};

#endif //KAMISADO_ENUM_UTILS_H
